In [1]:
import numpy as np 
np.__version__

'1.18.1'

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.ones((3,5),dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [9]:
np.random.normal(0,1,(3,3))


array([[-1.44564872,  0.93622715, -1.23939821],
       [ 1.59827985,  1.70034744, -0.04214606],
       [-0.91026297,  0.89394565, -0.58743982]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.seed(0)

In [13]:
x1 = np.random.randint(10,size = 6)
x1

array([3, 5, 2, 4, 7, 6])

In [15]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[4, 3, 0, 3],
       [5, 0, 2, 3],
       [8, 1, 3, 3]])

In [17]:
x3 = np.random.randint(10,size = (3,4,5))
x3

array([[[1, 2, 4, 2, 0],
        [3, 2, 0, 7, 5],
        [9, 0, 2, 7, 2],
        [9, 2, 3, 3, 2]],

       [[3, 4, 1, 2, 9],
        [1, 4, 6, 8, 2],
        [3, 0, 0, 6, 0],
        [6, 3, 3, 8, 8]],

       [[8, 2, 3, 2, 0],
        [8, 8, 3, 8, 2],
        [8, 4, 3, 0, 4],
        [3, 6, 9, 8, 0]]])

In [21]:
x1 = np.array([4,3,4,4,8,4])
x1

array([4, 3, 4, 4, 8, 4])

In [24]:
x1[-1]

4

In [30]:
x1[4:]


array([8, 4])

In [31]:
x1[: : 2]

array([4, 4, 8])

In [32]:
x1[1::2]

array([3, 4, 4])

In [34]:
x1[::-1]

array([4, 8, 4, 4, 3, 4])

In [35]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = [21,21,21]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [37]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([grid,grid],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])


array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [41]:
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x1,x2,x3 = np.split(x,[3,6]) 
print (x1,x2,x3)

[0 1 2] [3 4 5] [6 7 8 9]


In [47]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
upper,lower = np.vsplit(grid,[2])
print(upper,lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
